name: ausem
channels:
  - conda-forge
dependencies:
  - pip=25.0
  - python=3.11
  - pip:
      - arrow==1.3.0
      - datasets==3.3.1
      - huggingface-hub==0.28.1
      - jupyter==1.1.1
      - matplotlib==3.10.0
      - notebook==7.3.2
      - numpy==1.25.2
      - pandas==2.2.3
      - pyyaml==6.0.2
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - seaborn==0.13.2
      - torch==2.6.0
      - torchvision==0.21.0
      - transformers==4.48.2
      - wandb==0.19.6
