embedder: bow
criteria_embedder: identity
combiner: concatenate
device: cpu
finetune: false
wandb_project: sensemaking_bert_bow
seed: 360
num_epochs: 1000
loss: bce
use_wandb: false
num_folds: 1
val_freq: 1
learning_rate: 0.01
opt_weight_decay: 0.001
batch_size: N
experiment_name: test15_lr0.01_wd0.001_bsN
train_x_file: ./Student_Explanations/clean/test_15/retrain_x.csv
train_y_file: ./Student_Explanations/clean/test_15/retrain_y.csv
val_x_file: ./Student_Explanations/clean/test_15/test_x.csv
val_y_file: ./Student_Explanations/clean/test_15/test_y.csv
test_x_file: ./Student_Explanations/clean/test_15/fold_{fold}/test_x.csv
test_y_file: ./Student_Explanations/clean/test_15/fold_{fold}/test_y.csv
train_metrics_path: ./output/bow_test/test15_lr0.01_wd0.001_bsN/train_metrics.csv
val_metrics_path: ./output/bow_test/test15_lr0.01_wd0.001_bsN/val_metrics.csv
final_model_path: ./output/bow_test/test15_lr0.01_wd0.001_bsN/final_model.pth
