embedder: bert
criteria_embedder: identity
combiner: concatenate
opt_weight_decay: 0
device: cuda
finetune: true
wandb_project: 20250301_sensemaking_bert_finetune_test
bert_model_name: bert-base-uncased
seed: 360
num_epochs: 1000
loss: l2sp
num_folds: 1
val_freq: 20
learning_rate: 1.0e-05
alpha: 0.0001
beta: 0.1
batch_size: 32
experiment_name: test15_lr1e-05_alpha0.0001_beta0.1
train_x_file: ./Student_Explanations/clean/test_15/retrain_x.csv
train_y_file: ./Student_Explanations/clean/test_15/retrain_y.csv
val_x_file: ./Student_Explanations/clean/test_15/test_x.csv
val_y_file: ./Student_Explanations/clean/test_15/test_y.csv
test_x_file: ./Student_Explanations/clean/test_15/test_x.csv
test_y_file: ./Student_Explanations/clean/test_15/test_y.csv
train_metrics_path: ./output/test15_lr1e-05_alpha0.0001_beta0.1/train_metrics.csv
val_metrics_path: ./output/test15_lr1e-05_alpha0.0001_beta0.1/val_metrics.csv
final_model_path: ./output/test15_lr1e-05_alpha0.0001_beta0.1/final_model.pth
